ALTER TABLE {$prefix}posts CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}postinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}posttype CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}poststatus CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}options CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}users CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}userinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}tags CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}tag2post CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}comments CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}commentinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}rewrite_rules CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}crontab CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}log CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}log_types CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}groups CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}users_groups CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}groups_permissions CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}sessions CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}posts CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}postinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}posttype CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}poststatus CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}options CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}users CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}userinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}tags CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}tag2post CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}comments CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}commentinfo CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}rewrite_rules CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}crontab CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}log CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}log_types CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}groups CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}users_groups CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}groups_permissions CONVERT TO CHARACTER SET binary;
ALTER TABLE {$prefix}sessions CONVERT TO CHARACTER SET binary;

ALTER TABLE {$prefix}posts CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}postinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posttype CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}poststatus CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}options CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}userinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tags CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tag2post CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}comments CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}commentinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}rewrite_rules CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}crontab CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log_types CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}sessions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posts CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}postinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posttype CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}poststatus CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}options CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}userinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tags CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tag2post CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}comments CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}commentinfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}rewrite_rules CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}crontab CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log_types CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}sessions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE {$prefix}posts DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}postinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posttype DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}poststatus DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}options DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}userinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tags DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tag2post DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}comments DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}commentinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}rewrite_rules DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}crontab DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log_types DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users_groups DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups_permissions DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}sessions DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posts DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}postinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}posttype DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}poststatus DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}options DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}userinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tags DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}tag2post DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}comments DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}commentinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}rewrite_rules DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}crontab DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}log_types DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}users_groups DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}groups_permissions DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE {$prefix}sessions DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE {$prefix}posts modify column content longtext;
ALTER TABLE {$prefix}posts modify column cached_content longtext;
ALTER TABLE {$prefix}postinfo modify column value text;
ALTER TABLE {$prefix}postinfo modify column value text;
ALTER TABLE {$prefix}options modify column value text;
ALTER TABLE {$prefix}userinfo modify column value text;
ALTER TABLE {$prefix}comments modify column content text;
ALTER TABLE {$prefix}commentinfo modify column value text;
ALTER TABLE {$prefix}rewrite_rules modify column description text;
ALTER TABLE {$prefix}crontab modify column description text;
ALTER TABLE {$prefix}sessions modify column data mediumtext;
